blog/urls.py
from django.urls import path, re_path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),

    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),

    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

bookmark/urls.py
from django.urls import path

from bookmark import views

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('bookmark/<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path("admin/", admin.site.urls),
    #인증
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    path('bookmark/', include('bookmark.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmark/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from bookmark.models import Bookmark
from mysite.views import OwnerOnlyMixin


# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

bookmark/templates/bookmark/bookmark_change_list.html
{% extends 'base.html' %}
{% block title %}bookmark_chage_list.html{% endblock title %}
{% block content %}
    <h1>Bookmark Change - {{ user }}</h1>
    <br>
    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Url</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                <tr>
                    <td>{{ item.title }}</td>
                    <td>{{ item.url }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'bookamrkupdate' item.id">Update</a></td>
                    <td><a href="{% url 'bookmark:delete' item.id">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}bookmark_confirm_delete.html{% endblock title %}

{% block content %}
    <h1>Bookmark Delete</h1>
    <br>

    <form action="." method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
    </form>
{% endblock content %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %}bookmark_detail.html{% endblock title %}
{% block content %}
<div id="content">
    <h1>
        {{ object.title }}
    </h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
</div>
{% endblock content %}

bookmark/templates/bookmark/bookmark_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}bookmark_form.html{% endblock title %}

{% block content %}
    <h1>Bookmark Create/Update - {{ user }}</h1>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the error(s).</div>
            {{ form.errors }}
        </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">
        {% csrf_token %}
        <div class="form-group row">
            {{ form.title|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.title|add_class:'form-control'|attr:'autofocus' }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.url|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.url|add_class:'form-control' }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info">
            </div>
        </div>
    </form>

{% endblock content %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block title %}bookmark_list.html{% endblock title %}

{% block content %}
<div id="content">
    <h1>Bookmark List</h1>
    <ul>
        {% for bookmark in object_list %}
            <li>
                <a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
{% endblock content %}