blog/urls.py
from django.urls import path, re_path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),

    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),

    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path("admin/", admin.site.urls),
    #인증
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    path('bookmark/', include('bookmark.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from taggit.managers import TaggableManager


# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    created_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

blog/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, ArchiveIndexView, YearArchiveView, MonthArchiveView, \
    DayArchiveView, TodayArchiveView, TemplateView, FormView, CreateView, UpdateView, DeleteView

from blog.forms import PostSearchForm
from blog.models import Post
from mysite.views import OwnerOnlyMixin


# Create your views here.
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2


class PostDV(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}"
        return context


class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    # month_format = '%b'


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    month_format = '%m'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    month_format = '%m'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'
    template_name = 'blog/post_archive_day.html'


class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'


class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | Q(description__icontains=searchWord) | Q(
            content__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:index')


class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
{% extends 'base.html' %}

{% block content %}
    <h1>Blog List</h1>
    <br>

    {% for post in posts %}
        <h3><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
        {{ post.modify_dt|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    {% endfor %}

    <br>

    <div>
    <span>
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
        {% endif %}

        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
        {% endif %}
    </span>
    </div>
{% endblock %}

blog/templates/blog/post_archive.html
{% extends 'base.html' %}

{% block content %}
    <h1>Post Archives until {% now "N d, Y" %}</h1>

    <ul>
        {% for date in date_list %}
            <li style="display: inline">
                <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">
                    Year {{ date|date:'Y' }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
                <li class="h5">
                    {{ post.modify_dt|date:'Y-m-d' }}&emsp;
                    <a href="{{ post.get_absolute_url }}">
                        <strong>{{ post.title }}</strong>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}

{% block content %}
    <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
                <li class="h5">
                    {{ post.modify_dt|date:'Y-m-d' }}&emsp;
                    <a href="{{ post.get_absolute_url }}">
                        <strong>{{ post.title }}</strong>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}

{% block content %}
    <h1>Post Archives for {{ month|date:"N, Y" }}</h1>

    <div>
        <ul>
            {% for post in object_list %}
                <li class="h5">
                    {{ post.modify_dt|date:'Y-m-d' }}&emsp;
                    <a href="{{ post.get_absolute_url }}">
                        <strong>{{ post.title }}</strong>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}

{% block content %}
    <h1>Post Archives for {{ year|date:'Y' }}</h1>

    <ul>
        {% for date in date_list %}
            <li style="display: inline">
                <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'m' %}">
                    {{ date|date:'F' }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <br>

    <div>
        <ul>
            {% for post in object_list %}
                <li class="h5">
                    {{ post.modify_dt|date:'Y-m-d' }}&emsp;
                    <a href="{{ post.get_absolute_url }}">
                        <strong>{{ post.title }}</strong>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

blog/templates/blog/post_change_list.html
{% extends 'base.html' %}

{% block title %}post_change_list.html{% endblock title %}

{% block content %}
    <h1>Post Change - {{ user }}</h1>
    <br>
    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
                <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}post_confirm_delete.html{% endblock title %}

{% block content %}
    <h1>Post Delete</h1>
    <br>

    <form action="." method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
    </form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ object.title }}</h2>

    <p>
        {% if object.get_previous %}
            <a href="{{ object.get_previous.get_absolute_url }}">
                <i class="fas fa-arrow-circle-left"></i> {{ object.get_previous }}
            </a>
        {% endif %}
        <!--&nbsp;&nbsp;-->
        {% if object.get_next %}
            <a href="{{ object.get_next.get_absolute_url }}">
                {{ object.get_next }} <i class="fas fa-arrow-circle-right"></i>
            </a>
        {% endif %}
    </p>

    <p>
        {{ object.modify_dt|date:"j F Y" }}
    </p>

    <div>
        {{ object.content|linebreaks }}
    </div>
    <br>
<div id="disqus_thread"></div>
{% endblock content %}

{% block extra-script %}
    <script>
        var disqus_config = function () {
            this.page.identifier = '{{ disqus_id }}';
            this.page.url = '{{ disqus_url }}';
            this.page.title = '{{ disqus_title }}';
        };

        (function () {
            var d = document, s = d.createElement('script');
            s.src = 'https://{{ disqus_short }}.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head||d.body).appendChild(s);
        })();
    </script>
    <noscript>Please enable JavasScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>
{% endblock extra-script %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}post_form.html{% endblock title %}

{% block content %}
    <h1>Post Create/Update - {{ user }}</h1>
    <p class="font-italic">
        This is a creation or update form for your post.
    </p>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please crrect the error(s) below.</div>
            {{ form.errors }}
        </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">
        {% csrf_token %}
        <div class="form-group row">
            {{ form.title|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.title|add_class:'form-control'|attr:'autofocus' }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.slug|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.slug|add_class:'form-control'|attr:'readonly' }}
            </div>
            <small class="form-text text-muted">
                {{ form.slug.help_text}}
            </small>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.description|add_class:'form-control' }}
            </div>
            <small class="form-text text-muted">
                {{ form.description.help_text}}
            </small>
        </div>

        <div class="form-group row">
            {{ form.content|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.content|add_class:'form-control' }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.tags|add_label_class:'col-form-label col-sm-2 ml-3 font-weight-bold' }}
            <div class="col-sm-5">
                {{ form.tags|add_class:'form-control' }}
            </div>
            <small class="form-text text-muted">
                {{ form.tags.help_text}}
            </small>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info">
            </div>
        </div>
    </form>

{% endblock content %}

blog/templates/blog/post_search.html
{% extends 'base.html' %}

{% block title %}post_search.html{% endblock title %}

{% block content %}
    <h1>Blog Search</h1>

    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>

    <br><br>
    {% if object_list %}
        {% for post in object_list %}
            <h2>
                <a href="'{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h2>
            <p>{{ post.description }}</p>
        {% endfor %}

    {% elif search_term %}
        <b><i>Search Word({{ searh_term }}) Not Found</i></b>
    {% endif %}
{% endblock content %}