blog/urls.py
from django.urls import path, re_path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),

    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),

    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path("admin/", admin.site.urls),
    #인증
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    path('bookmark/', include('bookmark.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from photo import views

app_name = 'photo'

urlpatterns = [
    path('', views.AlbumLV.as_view(), name='index'),

    path('album', views.AlbumLV.as_view(), name='album_list'),

    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),
]

photo/models.py
from django.db import models
from django.urls import reverse

from photo.fields import ThumbnailImageField


# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    upload_dt = models.DateTimeField('Uploaded Date', auto_now_add=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

photo/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from photo.models import Album, Photo


# Create your views here.
class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo

photo/templates/photo/album_detail.html
{% extends 'base.html' %}

{% block title %}album_detail.html{% endblock title %}

{% block extra-style %}
    <style>
        .thumbnail {
            border: 5px solid #ccc;
        }

        .thumbnail img {
            width: 100%;
        }
    </style>
{% endblock extra-style %}

{% block content %}
    <div class="mt-5">
        <span class="h2">
            {{ object.name }}&emsp;
        </span>
        <span class="h5 font-italic">
            {{ object.description }}
        </span>
    </div>

    <hr style="margin:0 0 20px 0;">

    <div class="row">
        {% for photo in object.photo_set.all %}
            <div class="col-md-3 mb-5">
                <div class="thumbnail">
                    <a href="{{ photo.get_absolute_url }}">
                        <img src="{{ photo.image.thumb_url }}" alt="">
                    </a>
                </div>
                <ul>
                    <li class="font-italic">{{ photo.title }}</li>
                    <li class="font-italic">{{ photo.upload_dt|date:'Y-m-d' }}</li>
                </ul>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

photo/templates/photo/album_list.html
{% extends 'base.html' %}

{% block title %}album_list.html{% endblock title %}

{% block extra-style %}
    <style>
        .thumbnail {
            border: 3px solid #ccc;
        }
    </style>
{% endblock extra-style %}

{% block content %}
    {% for item in object_list %}
        <div class="mt-5">
            <a href="{% url 'photo:album_detail' item.id %}">{{ item.name }}</a>
            <span class="font-italic h5">{{ item.description }}</span>
        </div>

        <hr style="margin-bottom: 20px;">

        <div class="row">
            {% for photo in item.photo_set.all|slice:":5" %}
                <div class="ml-5">
                    <div class="thumbnail">
                        <a href="{{ photo.get_absolute_url }}">
                            <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>

    {% endfor %}
{% endblock content %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

{% block title %}photo_detail.html{% endblock title %}

{% block content %}
    <h2 class="mt-5">{{ object.title }}</h2>

    <div class="row">
        <div class="col-md-9">
            <a href="{{ object.image.url }}">
                <img src="{{ object.image.url }}" alt="" style="width:100%">
            </a>
        </div>
        <ul class="col-md-3 mt-3">
            <li class="h5">Photo Description</li>
            {% if object.description %}
                <p>{{ object.description|linebreaks }}</p>
            {% else %}
                <p>(blank)</p>
            {% endif %}
            <li class="h5">Date Uploaded</li>
            <p class="font-italic">{{ object.upload_dt }}</p>
            <li class="h5">Album Name</li>
            <p class="font-italic">
                <a href="{% url 'photo:album_detail' object.album.id %}">
                    {{ object.album.name }}
                </a>
            </p>
        </ul>
    </div>
{% endblock content %}