blog/urls.py
from django.urls import path, re_path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),

    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    path('archive/', views.PostAV.as_view(), name='post_archive'),

    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),

    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

bookmark/urls.py
from django.urls import path

from bookmark import views

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('bookmark/<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from bookmark.views import BookmarkLV, BookmarkDV
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

urlpatterns = [
    path("admin/", admin.site.urls),
    #인증
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    path('bookmark/', include('bookmark.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from photo import views

app_name = 'photo'

urlpatterns = [
    path('', views.AlbumLV.as_view(), name='index'),

    path('album', views.AlbumLV.as_view(), name='album_list'),

    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),
]

templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Django Web Programming{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    {% block extra-style %}{% endblock %}
</head>
<body style="padding-top: 90px">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <a class="navbar-brand" href="#">NavBar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link">
                    Home <span class="sr-only">current</span>
                </a>
            </li>
            <li class="nav-item dropdown mx-1">
                <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">Bookmark</a>
                <div class="dropdown-menu">
                    <a href="{% url 'bookmark:index' %}" class="dropdown-item">List</a>
                    <a href="{% url 'bookmark:add' %}" class="dropdown-item">Add</a>
                    <a href="{% url 'bookmark:change' %}" class="dropdown-item">Change</a>
                </div>
            </li>
            <li class="nav-item dropdown mx-1">
                <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">Blog</a>
                <div class="dropdown-menu">
                    <a href="{% url 'blog:index' %}" class="dropdown-item">List</a>
                    <a href="{% url 'blog:add' %}" class="dropdown-item">Add</a>
                    <a href="{% url 'blog:change' %}" class="dropdown-item">Change</a>
                </div>
            </li>
            <li class="nav-item dropdown mx-1">
                <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">Photo</a>
                <div class="dropdown-menu">
                    <a href="{% url 'photo:index' %}" class="dropdown-item">List</a>
                    <a href="{% url 'home' %}" class="dropdown-item">Add</a>
                    <a href="{% url 'home' %}" class="dropdown-item">Change</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button"
                   data-toggle="dropdown">
                    Util
                </a>
                <div class="dropdown-menu">
                    <a href="{% url 'admin:index' %}" class="dropdown-item" target="_blank">Admin</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'blog:post_archive' %}" class="dropdown-item">Archive</a>
                    <a href="{% url 'blog:search' %}" class="dropdown-item">Search</a>
                </div>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link disabled" tabindex="-1">Disabled</a>
            </li>

            <li class="nav-item dropdown">
                {% if user.is_active %}
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                    </a>
                    <div class="dropdown-menu">
                        <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
                        <a href="{% url 'password_change' %}" class="dropdown-item">Change Password</a>
                    </div>
                {% else %}
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&ensp;Anonymous&ensp;
                    </a>
                    <div class="dropdown-menu">
                        <a href="{% url 'login' %}" class="dropdown-item">Login</a>
                        <a href="{% url 'register' %}" class="dropdown-item">Register</a>
                    </div>
                {% endif %}
            </li>

        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'blog:search' %}" method="post">
            {% csrf_token %}
            <input type="search" class="form-control mr-sm-2" name="search_word" placeholder="입력해주세요.">
            <button type="submit" class="btn btn-outline-success my-2 my-sm-0">
                Search
            </button>
        </form>
    </div>
</nav>

<div class="container bg-warning">
    {% block content %}{% endblock content %}
</div>

{% block footer %}{% endblock footer %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="https://use.fontawesome.com/ee1c3da296.js"></script>
{% block extra-script %}{% endblock extra-script %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
 home.html
{% endblock title %}
    {% block extra-style %}
    <style type="text/css">
        .home-image {
            background-image: url("{% static 'img/lion.jpg' %}");
            background-repeat: no-repeat;
            background-position: center;
            background-size: 100%;
            height: 500px;
            border-top: 10px solid #ccc;
            border-bottom: 10px solid #ccc;
            padding: 20px 0 0 20px;
        }

        .title {
            color: #c80;
            font-weight: bold;
        }

        .powered {
            position: relative;
            top: 77%;
            color: #cc0;
            font-style: italic;
        }
    </style>
{% endblock extra-style %}

{% block content %}
<div class="home-image">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right">
        Powered by django and bootstrap.
    </i></h4>
</div>
<hr style="margin:10px 0">
<div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>Bookmark is a Uniform Resource Identifier (URI)
                that is stored for later retrieval in any of various storage formats.
                You can store your own bookmarks by Bookmark application.
                It's also possible to update or delete your bookmarks.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.</p>
        </div>
    </div>
{% endblock %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">
        Copyright &copy; 2023 DjangoBook by python6th
    </div>
</footer>
{% endblock footer %}